### ISSUE TITLE
Map data format

### ISSUE THREAD

**Issue by Elmetayer** [gflowiz/arabesque#21]
Hi arabesque project, would it be possible to get more information about the data format to use in order to load a map ?

**Comment by fbahoken** [comment]
You must at least have a .csv file that describes flow data, with at least these 3 columns: origin, destination, value of the origin-destination flow.</br>
For an example, see this [RICardo file](https://raw.githubusercontent.com/gflowiz/sageo-ricardo/master/SAGEO_RICardo_nodes.csv)
For a tutorial, see [Sageo-Ricardo](https://github.com/gflowiz/sageo-ricardo)
