### ISSUE TITLE
Dead link on website

### ISSUE THREAD

**Issue by Robinlovelace** [gflowiz/arabesque#27]
Heads-up, I've been on the great website http://vlsstats.ifsttar.fr/gflowiz/

That contains this dead link: https://github.com/gflowiz/Glowiz-Arabesque

**Comment by bapaumet** [comment]
Hello,
http://vlsstats.ifsttar.fr/gflowiz/ is the old website with old github repository.

The new link is [http://arabesque.ifsttar.fr/](http://arabesque.ifsttar.fr/)

**Comment by Robinlovelace** [comment]
Thanks for the clarification @bapaumet. I've updated the URL in the package linking to this: https://github.com/ITSLeeds/od/commit/4abb32bca0e7f5d2d387a19c32f628456d8aebf6

If you spot any issues with that please let me know.
